quarkus.http.port=8081
#Definimos el tipo de base de datos que vamos a usar,
# en este caso PostgreSQL
quarkus.datasource.db-kind=postgresql
#usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
#password con el que se conecta a la base de datos a usar
quarkus.datasource.password=labcom,2015
#URL de conexion a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pas

#Sincroniza lo que tengo en codigo con la base de datos
quarkus.hibernate-orm.database.generation=update
#Cada vez que se ejecuta una consulta a la base de datos,
#Se muestra en la consola ese sql que se esta ejecutando
quarkus.hibernate-orm.log.sql=true

#Detecta la secuencia que no salga error
quarkus.hibernate-orm.sql-load-script=import.sql

